### ISSUE TITLE
Snap Hutao 2024 Roadmap

### ISSUE THREAD

**Issue by Lightczx** [DGP-Studio/Snap.Hutao#1394]
* [ ] 客户端
	* [x] 首次引导
		* [x] 加入主页公告服务器选项 #1287
	* [ ] UI/UX
		* [ ] 过长的文本应支持鼠标悬浮滚动显示 #863 #1505 
		* [x] 更新逻辑加入 用户确认开始下载 步骤 #1297
      	* [x] WebView2使用独立Window呈现 #1508
	* [ ] 页面
		* [ ] 主页仪表板
			* [ ] 加入每日原石/摩拉获取数量卡片，导航到米游社信息统计页面查看详情 #385
			* [ ] 加入探索度/宝箱数/神瞳数卡片，导航到米游社信息统计页面查看详情 #546
			* [ ] 加入原神签到卡片 #1322
			* [ ] 增加HoYoLAB/米游社 小工具合集支持 #1280 #1319
			* [x] 加入天赋/武器材料日历 #501 
		* [ ] 启动游戏
			* [ ] 增加游戏内设置修改/保存 #868 #1308
			* [x] 增加"预下载"下载与更新 #786
			* [x] Unlocker替换为启动前加载Library寻址
			* [ ] 通过符号链接实现更快的区服启动 #1524 
			* [x] 自定义快捷分辨率
		* [ ] 祈愿记录
			* [x] 增加角色/武器 距上次 UP 计时器 #1341
			* [ ] 登录胡桃通行证后自动上传到胡桃云 #1100
			* [x] 角色/武器页签显示未抽到的的物品0个 #1355
		* [ ] 成就管理
			* [x] 成就页面"成就分组"排序支持优先显示未完成的分组 #896
			* [ ] 成就页面加入成就触发/成就完成条件 #897 #1536 
			* [ ] 成就页面右键允许复制成就 Id
		* [x] 实时便笺
			* [x] 实时便笺卡片导航到启动游戏界面并选中对应的 UID #1318
			* [x] 实时便笺卡片增加魔神任务完成情况 #1203
		* [ ] 我的角色
			* [ ] 角色技能伤害计算 #42
			* [ ] 网格视图增加好感度显示 #1283
			* [x] 以文字形式复制角色面板 #1497 
		* [ ] 深境螺旋
			* [x] 未登录胡桃通行证上传时进行提示 #1245
			* [ ] 角色持有率支持排序 #1185 
			* [ ] 导入/导出深渊数据 #1507 
		* [ ] 资料
			* [ ] 家具
				* [ ] 加入家具资料页面，支持尘歌壶摹本码计算并添加至养成计划 #114 #217
			* [ ] 加入圣遗物资料页面 #272
			* [ ] 角色/怪物资料加入产球数据 #991
			* [x] 角色资料显示对应名片 #1424 
			* [ ] 角色资料添加养成攻略 #1526 
		* [ ] 养成计划页面，材料统计页签修改排序规则，按 Id 排序 #889 #1427
		* [x] 材料获取体力预估 #323 
		* [ ] 加入米游社信息统计页面
	* [ ] 导航
		* [ ] ItemIcon 支持右键菜单跳转到对应资料页面 #618
	* [ ] 窗口
		* [ ] 加入半透明悬浮窗展示养成物品/材料 #679 
	* [ ] 进程
		* [ ] 添加托管的 YaeAchievement，使用国内节点下载，托管版本，实现自动刷新成就数据 #950
		* [ ] 自动上传深渊挑战记录 #1100
		* [ ] 自动原神社区签到 #1180 
* [ ] 服务端
	* [ ] 通行证
		* [x] 支持修改邮箱
	* [ ] 云托管用户个人数据
		* [ ] 深渊记录 #1030
   * [ ] 兑换码系统
* [x] Deployment
   * [x] 反馈
      * [x] 主程序更新反馈 DGP-Studio/Snap.Hutao.Deployment#6

**Comment by AbyssMorax** [comment]
通过对比目录结构差异和文件MD5，我发现StreamingAssets的主体文件在相同版本几乎无差别，那么是否可以通过将不同版本的差异文件放一个目录，然后共同文件通过符号链接（cmd：mklink /d）来实现一种更快速的方式启动
